### ISSUE TITLE
🐞 [Bug]: Subspace CLI hits opened file limit

### ISSUE THREAD

**Issue by i1i1** [subspace/subspace-cli#123] opened 2023-03-12 08:00 UTC
### What happened?

Subspace CLI crashed due to hitting file limit while opening a farmer:
```
$ ./subspace-cli-macos-x86_64-v0.1.8-alpha farm
Starting node ...
Node started successfully!
 ◟  [01:21:24] 100% [███████████████████████████████████████████] (398826/398826) 81.65bps, Syncing is done!, ETA: 00:00:00 Starting farmer ...
Error: 
   0: IO Error: Too many open files (os error 24)
   1: IO Error: Too many open files (os error 24)

Location:
   src/commands/farm.rs:75
```

### Version

v0.1.7-alpha

### platform

- [X] linux
- [ ] windows
- [ ] macos

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by i1i1** [comment] 2023-03-12 12:30
Maybe https://github.com/subspace/subspace-sdk/pull/135 fixes it.

@ozgunozerk wild guess:
> I think, the node or farmer is not fully terminated, or at least the file descriptors that farmer/node are using are not becoming free.
And when restarting the cli, it hits the limit because of unfreed previous file descriptors.

**Comment by ozgunozerk** [comment] 2023-03-24 15:39
Closing, since this is not reproduced since v0.1.7

**Closed by ozgunozerk** 2023-03-24 15:39 UTC
Labels: bug
